name: WaitCore
version: 1.8.9.1
main: mc.waitpvp.settings.Core
author: YuDong
description: §c§l[WAIT NETWORK] §B§L專屬核心插件 §a使用/?獲取更多!
commands:
  waitreport:
    description: 開發中! 使用/report代替!
    aliases:
      - wreport
      - waitreports
      - waitreporthack
      - wdr
      - wtfreport
      - wtfhac
  howtoplay:
    description: 幹你娘怎麼玩
    aliases:
      - htp
      - howplay
  gmc:
    description: 切換創造
  gms:
    description: 切換生存
  gma:
    description: 切換冒險
  eatgigi:
    description: 吃ㄐㄐ模式，
  waitpvp:
    description: main-command
    aliases:
      - wait
      - waitaliases
      - waitcore
      - core
      - version
      - ver
      - cool
      - "?"
  mus:
    description: test command for DCJH
  gg:
    description: coming sooon
  resetname:
    description: nothing just reset nickname. like /unnick
  radius:
